name: Lint and Testing

on:
  push:

jobs:
  testing:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: update some text 1
        run: |
          openssl rand -hex 16 > test.txt

      - name: Updated changes from github actions
        uses: ./
        with:
          author_email: 41898282+github-actions[bot]@users.noreply.github.com
          author_name: GitHub Actions
          branch: branch01
          commit: true
          fore: true
          commit_message: "[skip ci] Updated changes from github actions"
          remote: git@github.com:appleboy/git-push-action.git
          ssh_key: ${{ secrets.DEPLOY_KEY }}

      - name: update some text 2
        run: |
          openssl rand -hex 16 > test.txt

      - name: Updated changes from default user
        uses: ./
        with:
          branch: branch02
          commit: true
          fore: true
          commit_message: "[skip ci] Updated changes from default user"
          remote: git@github.com:appleboy/git-push-action.git
          ssh_key: ${{ secrets.DEPLOY_KEY }}

      - name: update some text 3
        run: |
          openssl rand -hex 16 > test.txt

      - name: Updated changes by gitea bot
        uses: ./
        with:
          author_email: teabot@gitea.io
          author_name: GiteaBot
          branch: branch03
          commit: true
          fore: true
          commit_message: "[skip ci] Updated changes by gitea bot"
          remote: git@github.com:appleboy/git-push-action.git
          ssh_key: ${{ secrets.DEPLOY_KEY }}
